version: '3.8'
services:

  app:
    image: heisyenberg/spring-book-shop:1.0
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: spring_book
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./public/images:/app/public/images
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring_book
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql