DROP DATABASE IF EXISTS spring_book;

CREATE DATABASE spring_book;

-- Switch to spring_book database

CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255),
    author      VARCHAR(255),
    genre       VARCHAR(255),
    price       DOUBLE PRECISION,
    description TEXT,
    image_name  VARCHAR(255)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    email    VARCHAR(255) NOT NULL
        CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE,
    password VARCHAR(255) not null,
    role     VARCHAR(255)
);